In [57]:
from sklearn.datasets import load_iris

In [79]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [59]:
import pandas as pd
import numpy as np

In [60]:
np.random.seed(0)

In [61]:
iris=load_iris()
#creating a dataframe with the four feature variables
df=pd.DataFrame(iris.data,columns=iris.feature_names)
#viewing the rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [62]:
df['Target as flower']=pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Target as flower  
0           setosa  
1           setosa  
2           setosa  
3           setosa  
4           setosa

In [77]:
df['is_train']=np.random.uniform(0,1,len(df))<=.7
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Target as flower  is_train  
0           setosa     False  
1           setosa     False  
2           setosa      True  
3           setosa      True  
4           setosa      True

In [64]:
train,test=df[df['is_train']==True],df[df['is_train']==False]
#show the number of observation for the test and train dataframes
print('Number of Training data',len(train))
print('Number of Test data',len(test))

Number of Training data 111
Number of Test data 39


In [65]:
features=df.columns[:4]
print(features)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')


In [66]:
y=pd.factorize(train['Target as flower'])[0]
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [67]:
clf=RandomForestClassifier(n_jobs=2,random_state=0)
#training the classifier
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [68]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [69]:
clf.predict_proba(test[features])[0:10]

array([[0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [70]:
preds=iris.target_names[clf.predict(test[features])]
#view the predicted species for the first five observation
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [71]:
test['Target as flower'].head()

1     setosa
7     setosa
8     setosa
10    setosa
13    setosa
Name: Target as flower, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [72]:
pd.crosstab(test["Target as flower"],preds, rownames=['Actual Flower'],colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Flower                                   
setosa                 14           0          0
versicolor              0           7          2
virginica               0           0         16

In [75]:
accuracy=(14+7+16)/39*100
print(accuracy)

94.87179487179486


In [74]:
clf.predict([[3,3,2,2]])

array([0])

NameError: name 'y_test' is not defined